notifications:
  email:
  - apple.builds@sagebase.org
language: objective-c
osx_image: xcode11
xcode_workspace: mPower2.xcworkspace
xcode_scheme: mPower2
cache:
- bundler
- cocoapods
addons:
  homebrew:
    packages: python3
before_install:
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
  - pip3 install virtualenv
  - virtualenv -p python3 ~/venv
  - source ~/venv/bin/activate
install:
- pip install travis-wait-improved
- gem install bundler
- bundle install
script:
  - travis-wait-improved --timeout 60 ./travis/build.sh
branches:
  only:
  - master
  - "/^stable-.*$/"
